import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#3c2f00',
        'surface-container-high': '#2a2a2a',
        'error-container': '#93000a',
        'on-surface': '#e5e2e1',
        'surface-tint': '#e9c349',
        'surface-dim': '#131313',
        primary: '#f2ca50',
        'primary-container': '#d4af37',
        'outline-variant': '#4d4635',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed': '#1c1b1b',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e1',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed-variant': '#474746',
        'inverse-primary': '#735c00',
        'secondary-container': '#474746',
        'inverse-surface': '#e5e2e1',
        'surface-bright': '#3a3939',
        'tertiary-fixed': '#e2e2e2',
        'surface-variant': '#353534',
        'on-error': '#690005',
        'tertiary-container': '#b2b3b3',
        'on-surface-variant': '#d0c5af',
        error: '#ffb4ab',
        'on-secondary-container': '#b7b5b4',
        'on-secondary': '#313030',
        'secondary-fixed-dim': '#c8c6c5',
        secondary: '#c8c6c5',
        'on-primary-fixed': '#241a00',
        'inverse-on-surface': '#313030',
        background: '#131313',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-highest': '#353534',
        'on-tertiary': '#2f3131',
        'surface-container': '#201f1f',
        'on-primary-container': '#554300',
        'on-tertiary-fixed-variant': '#454747',
        outline: '#99907c',
        surface: '#131313',
        'on-tertiary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#574500',
        tertiary: '#cecece',
        'primary-fixed-dim': '#e9c349',
        'on-tertiary-container': '#444546',
        'secondary-fixed': '#e5e2e1',
        'primary-fixed': '#ffe088',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1440px',
        unit: '8px',
        'margin-edge': '64px',
        'section-gap': '128px',
      },
      fontFamily: {
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'sans-serif'],
        'headline-lg': ['var(--font-noto-serif)', 'serif'],
        'label-caps': ['var(--font-inter)', 'sans-serif'],
        'headline-md': ['var(--font-noto-serif)', 'serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'headline-display': ['var(--font-noto-serif)', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '300' }],
      },
    },
  },
  plugins: [],
}

export default config
